import streamlit as st
from PIL import Image
from predictor import predict_engagement

st.set_page_config(page_title="Social Media Engagement Predictor", page_icon="📈")
st.title("📈 Social Media Engagement Predictor")
st.caption("Predictive Model for Social Media Post Engagement")

uploaded = st.file_uploader("Upload your proposed post", type=["jpg","jpeg","png","webp"])
image = None
if uploaded:
    image = Image.open(uploaded).convert("RGB")
    st.image(image, caption="Your proposed post", use_container_width=True)
    st.caption(f"Image dimensions: {image.width} × {image.height}")

st.markdown("### Post information")
caption = st.text_area("Caption", placeholder="Enter the caption...")
c1, c2 = st.columns(2)
with c1:
    day = st.selectbox("Posting day", ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
    hour = st.slider("Posting hour", 0, 23, 19)
    media = st.selectbox("Media type", ["1","2","8","unknown"])
with c2:
    product = st.selectbox("Product type", ["feed","clips","carousel_container","unknown"])
    has_audio = st.checkbox("Has audio")
    paid = st.checkbox("Paid partnership")
carousel = st.number_input("Carousel items", min_value=1, max_value=20, value=1)

if st.button("🔮 Predict Engagement", type="primary", use_container_width=True):
    if not caption.strip():
        st.warning("Please enter a caption.")
    else:
        day_num = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].index(day)
        width = image.width if image else 1080
        height = image.height if image else 1350
        result = predict_engagement(caption, hour, day_num, media, product,
                                     width, height, has_audio, paid, carousel)
        st.success("Prediction complete!")
        a, b = st.columns(2)
        with a:
            st.metric("Predicted Engagement", f"{result['predicted_engagement']:,.0f}")
        with b:
            st.metric("Engagement Level", result["level"])
        st.write("Prediction generated by the trained machine-learning model.")

st.divider()
st.caption("Shire Moses Zimuzor • Reg. No. 2022813035")
